### ISSUE TITLE
slidify + RStudio

### ISSUE THREAD

**Issue by sherbrich** [ramnathv/slidify#128]
In following your "slidify + RSudio: a demo", everything works up until the point of publishing the slides. When I attempt to publish to the appropriate GitHub repository there is no error but the page never appears. Then when attempting to publish instead to RPubs I get the following error from RStudio:

Error in function (type, msg, asError = TRUE)  : 
  SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Calls: rpubsUpload ... <Anonymous> -> .postForm -> .Call -> <Anonymous> -> fun
Execution halted

I am using the most up to date versions of R, RStudio, and slidify.

Thanks,

Shelley

**Comment by yutsaichen** [comment]
I runned this  
install_github("slidify", "ramnathv")
then it came out this
Error: Command failed (1)
In addition: Warning message:
Username parameter is deprecated. Please use ramnathv/slidify
I don't know what this mean

**Comment by KOSUNGWOO** [comment]
I have a deck created using slidify and when I knit it, the slides show up in the preview window, but when i tried to publish it to rpubs by clicking the publish button on the pewview window, I got a blank slides published in rpubs.

I have followed the instructions on the slidify instructions and I do not know what is causing this issue and how to work around that. I have tried by directly clicking publishing and also by using the function publish_rpubs, but neither worked.

I can publish other outputs (like rmakrdown) without problem. 

![1](https://cloud.githubusercontent.com/assets/24269898/20750571/ed6571ca-b73a-11e6-9c38-9c2c33531758.JPG)
![2](https://cloud.githubusercontent.com/assets/24269898/20750574/f15de744-b73a-11e6-8c93-032181d060ee.JPG)

**Comment by ramnathv** [comment]
For `Rpubs`, you would need to set `mode: standalone` in your YAML.

**Comment by KOSUNGWOO** [comment]
Thanks for reply Ramnath. 
Although I've set mod: standalone in my YAML and knitted , 

Preveiw HTML and Rpubs shows only plain HTML format. 
It lost slide format..

I use window 10, and latest version of R and Rstudio. 

What am I doing wrong? 

![ask](https://cloud.githubusercontent.com/assets/24269898/20774628/7de21b4a-b79a-11e6-95f9-7f19dad64a10.JPG)

**Comment by KOSUNGWOO** [comment]
and as your comment above, 

i've copied .Rprofile in my working directory, 
and added options(rpubs.upload.method = "internal") as attached image file.

But when i knit and published to Rpbus, 
it still loses slide format..

I'd appreciate if you advise about my probelm 

Thanks!
