### ISSUE TITLE
Force line breaks in title slide fields

### ISSUE THREAD

**Issue by RyanHope** [ramnathv/slidify#135]
How can I force a line break in markdown. What I am trying to accomplish is have a multiline "job" field on my title page where I have my affiliation/institution under my department.

**Comment by jvcasillas** [comment]
I have a long title that needs to be parsed onto two lines; however, the natural split that slidify provides is too close to right-hand margin. Is there a way to force a line break in the `title` field?

**Comment by cmohamma** [comment]
I also have the same issue...
