### ISSUE TITLE
Make it Easy to Publish a Slidify Presentation

### ISSUE THREAD

**Issue by ramnathv** [ramnathv/slidify#14]
It would be useful to think about either a utility function, or a tutorial on how to publish a slidify presentation. Two options that come to my mind are:
1. Github
2. Dropbox

For github, it would be relatively straightforward to write a utility function, while for dropbox, I might consider rDrop which looks promising.

**Comment by tonosan** [comment]
I wonder how you can publish your slidify in sites.google.

**Comment by tonosan** [comment]
Hi
I´ll publish my slidify in rpubs but the presentation doesn´t appear.
Any idea of what is happening? thanks

---

title       : Introduccion a R 
subtitle    : Breve, muy breve
author      : Antonio Martinez Pineda
job         : Division de Educacion Continua Fac. Psicologia
logo        : dec.jpg
framework   : io2012  # {io2012, html5slides, shower, dzslides,revealjs, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # {tomorrow,zenburn,kate,tango,pygments}
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {selfcontained,standalone, draft}

## knit        : slidify::knit2slides

**Comment by Mechaque** [comment]
I am trying to publish my slide but it just shows a blank page nothing happens. any solutions you can share?
