### ISSUE TITLE
[Feature request] biblatex/bibtex support

### ISSUE THREAD

**Issue by RyanHope** [ramnathv/slidify#154]
In order to really compete with Beamer for presentations Slidify needs a way of accessing biblatex/bibtex databases for citations.

**Comment by bnicenboim** [comment]
Sorry to wake up this old request, but is this still relevant?, is knitcitations the only option?
I've tried to use this method: http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html
without success, but then [here](http://stackoverflow.com/questions/31221981/how-do-i-add-citations-and-a-bibliography-to-rpres-rmarkdown-presentations), it is as if it should work...
