### ISSUE TITLE
Changing font size for all slides?

### ISSUE THREAD

**Issue by andrewejaffe** [ramnathv/slidify#158]
Hey,

I really like the ideas behind slidify, and plan on using it to teach my R class shortly. However, I'm a relative novice at CSS and JS - is there an easy way to make the font bigger on every side? Basically I'm asking how to change the default font size. Here is my header slide:

title       : Lecture 1
subtitle    : Introduction to R
author      : [redacted] # i took out 
job         : [redacted] # i took out
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : prettify  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}

Thanks a ton!!

**Comment by annoporci** [comment]
Is this still the recommended approach? as of January 2015? Thanks!

**Comment by LL8054** [comment]
Hi Ramnath,

I tried copying the slidify.css file from libraries/frameworks/io2012/css to assets/css and it didn't retain my fonts, font sizes, and background colors when I published to rpubs.  What do I have to do to retain those changes?
