### ISSUE TITLE
Quiz Widget Examples

### ISSUE THREAD

**Issue by trinker** [ramnathv/slidify#196]
Ramnath,

Loving the slidify work.  I'm attempting to use it for multiple purposes and have used it for ecery lecture I've given since I learned about it.  One piece I haven't explored is the widgets.  I'm working with the Quiz widget this week.  Your examples usually use the radio slide but I know others exist (e.g. text).

I'm requesting a set of slides demoing all the capabilities with the quiz widget.

Again I appreciate all you've done with slidify and I know documentation will come but your examples are often the best documentation.

**Comment by JamesBorn** [comment]
Hi! Ramnath,
There is no  regular question for my slidify demo.
I use this command:
install_github("ramnathv/slidify")
install_github("ramnathv/slidifyLibraries")
library(slidify)
slidify("index.Rmd")
after that, this is my YAML

---
title       : Interactive Documents with R
subtitle    : Slidify + Shiny
author      : Ramnath Vaidyanathan
job         : Ramnath Vaidyanathan
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : solarized_light     # 
widgets     : [bootstrap, quiz]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---       
 

## interactive quizz

what is 1+1?

1. 1
2. _2_
3. 3


*** .hint

this a hint

*** .exploration

this is an exploration

when I use  browseURL("index.html") command, there is no regular question appears for the example

**Comment by derek-corcoran-barrios** [comment]
Hi Ramnath:

I have enjoyed using slidify, it is quite an amazing job that you have made. One question, is it possible when using the interactive quizz, instead of getting the results inmediately to get a grade at the end a la coursera? I want to do this with my students

Cheers

**Comment by ramnathv** [comment]
@derek-corcoran-barrios it would involve tweaking the widget logic. However, note that the student will be able to cheat, since the correct answer is marked up differently in the html. So a discerning student can always look up the source and figure out all the correct answers.

**Comment by derek-corcoran-barrios** [comment]
@ramnathv Thank you, I realize that they might cheat with that, but actually it is meant more for a self evaluation test, where they don't get the answer until the end, so they have to think a little bit more into that, besides, I believe that most of my students are not familiar with html.

Thank you
