### ISSUE TITLE
request for image position and resize

### ISSUE THREAD

**Issue by johnstantongeddes** [ramnathv/slidify#221]
Following up on my question from [stackoverlow](http://stackoverflow.com/questions/16904054/slidify-how-to-position-an-image): it seems that there is no option to specify the location or size of an image. While this makes sense at one level as the slides are written primarily in markdown, it is a barrier to transition from even something such as latex beamer which at least has the \includegraphics[width= ] option. I think adding options for location ("center", "top-right", etc) and size would tremendously increase adoption of slidify. As a novice in all this, no concrete suggestions on how to achieve it and I understand if this would be against the philosophy of slidify using just markdown.

**Comment by amir-rahnama** [comment]
+1 for this!
