### ISSUE TITLE
Suppressing slide numbers in io2012

### ISSUE THREAD

**Issue by webbedfeet** [ramnathv/slidify#234]
I'm sure this is pretty straighforward, but I want to suppress the slide numbers in io2012. 

On a side note, I notice that if I have a biglogo, the count for the first slide after the title page starts at 3. Can we make this 1?

Thanks for a great product.

**Comment by jvcasillas** [comment]
Is this still the preferred method for suppressing slide numbers? I tried both suggestions and they still appear.
