### ISSUE TITLE
Problem with nvd3 in slidify

### ISSUE THREAD

**Issue by maillot-jaune** [ramnathv/slidify#239]
I've been trying to incorporate some rCharts in a slidify presentation, but i get no love. I've installed the slidify package using the instructions from [http://slidify.org/start.html] and rCharts from [http://ramnathv.github.io/rCharts/].

From the commandline I do

 ~$ R -q -e 'slidify::author("script")'
 ~$ sudo nano -w script/index.Rmd

I replace all content in index.Rmd with [https://gist.github.com/ramnathv/bf55c9d47e461c037261]. Then I:

 ~$ R -q -e 'slidify::slidify("script/index.Rmd")'

processing file: index.Rmd
  |.............                                                    |  20%
  ordinary text without R code

  |..........................                                       |  40%
label: setup (with options) 
List of 2
 $ message: symbol F
 $ echo   : symbol F

  |.......................................                          |  60%
  ordinary text without R code

  |....................................................             |  80%
label: unnamed-chunk-1 (with options) 
List of 1
 $ echo: symbol F

  |.................................................................| 100%
  ordinary text without R code

output file: index.md

Copying files to libraries/frameworks/io2012...
Copying files to libraries/highlighters/highlight.js...
Copying files to libraries/widgets/nvd3...
Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> ... get_javascripts -> lapply -> FUN -> paste -> readLines -> file
In addition: Warning message:
In file(con, "r") :
  cannot open file 'libraries/widgets/nvd3/nvd3.html': No such file or directory
Execution halted

For some reason the nvd3 widget can't be copied. I can load other widgets (i.e. bootstrap) but not nvd3 or any other rCharts library. When I look into ../site-library/slidifyLibraries/libraries/widgets/ I see bootstrap, disqus, highlighters, mathjax and quiz.

When I look into ../site-library/rCharts/libraries I see datatables, highcharts, leaflet, morris, nvd3, polycharts, rickshaw, vega and xcharts. I've tried setting a soft link from the widgets folder pointing to ../site-library/rCharts/libraries/nvd3. The compilation then runs without error, but my index.html is not showing any graphs. However, there is a javascript inside index.html inidicating that someting relating to nvd3 is being done.

What am I doing wrong?

This is my sessionInfo():

R version 3.0.1 (2013-05-16)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C  
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8  
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8  
 [7] LC_PAPER=C                 LC_NAME=C  
 [9] LC_ADDRESS=C               LC_TELEPHONE=C  
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.2     slidify_0.3.3

loaded via a namespace (and not attached):
[1] digest_0.6.3   evaluate_0.4.3 formatR_0.7    markdown_0.5.4 stringr_0.6.2 
[6] tools_3.0.1    whisker_0.3-2  yaml_2.1.7

**Comment by CjTouzi** [comment]
Hi,
 I'm also trying asedgwick's example. 
I got this using the following code.  
![chart](https://cloud.githubusercontent.com/assets/9527598/6207715/7dc28b18-b5e4-11e4-89f8-9598f3a346a4.png)

```
---
title: Deck.js Template for Slidify
author: Ramnath Vaidyanathan
framework: deckjs
deckjs:
  theme: web-2.0
highlighter: highlight.js
hitheme    : solarized_light
ext_widgets: {rCharts: ["libraries/highcharts", "libraries/nvd3", "libraries/morris"]}    
mode : selfcontained
url:
  lib: ../../libraries
widgets: popcornjs
popcornjs:
  player: vimeo
  video: http://player.vimeo.com/video/41823197
---
```
## Graph 1
```{r setup, message = F, echo = F}

require(rCharts)
knitr::opts_chunk$set(comment = NA, results = 'asis', tidy = F, message = T, cache = F)
```
```{r chart1, echo=FALSE}
hair_eye_male <- subset(as.data.frame(HairEyeColor), Sex == "Male")
n1 <- nPlot(Freq ~ Hair, group = "Eye", data = hair_eye_male, type = "multiBarChart")
n1$print("chart3", include_assets=TRUE, cdn=TRUE)
```
If I change the last line to ```n1$print("chart3")```. The chart won't appear.

What am I doing wrong? One more question why it is chart3 in ```n1$print("chart3")``` but chart1 in ```{r chart1, echo=FALSE}```

Thanks a lot

**Comment by arturochian** [comment]
@CjTouzi  about this part {r chart1, echo=FALSE}  chart1 is the name of the chunk.
I normally work in this way

{r script1, echo=FALSE} 
{r chart1, echo=FALSE} 
{r chart2, echo=FALSE} 
{r script2, echo=FALSE}
and so on.

And this is not related to the print parameter. If I'm not wrong, this parameter is in order to give a name (I'm not sure). Perhaps your answer is related to that

PD: I didn't see this widget (popcornjs) before .

**Comment by CjTouzi** [comment]
@arturochian, thanks for your explanation about the chart name and your suggestion. 

About the  popcornjs, it's because I'm trying to put the multiBarChart into @ramnathv 's deckjs template. (Rmd file is here https://github.com/ramnathv/slidifyExamples/blob/gh-pages/examples/deckjs/deck-pop.Rmd.). 

As your mentioned, if I change it the same name, I still get the double chart as last post. 

```{r chart3, echo=FALSE}
hair_eye_male <- subset(as.data.frame(HairEyeColor), Sex == "Male")
n1 <- nPlot(Freq ~ Hair, group = "Eye", data = hair_eye_male, type = "multiBarChart")
n1$print("chart3", include_assets=TRUE, cdn=TRUE)
```

**Comment by CjTouzi** [comment]
@all, if I use default template, it works. So I guess it is because of the `deckjs`. Anyone can help. Thanks. 

![chart](https://cloud.githubusercontent.com/assets/9527598/6208884/5b8c3132-b5fa-11e4-8cbc-641c9c4327e6.png)


```
---
title       : test
ext_widgets : {rCharts: libraries/nvd3}
mode: selfcontained
---

```
```{r nvd3plot2, results = 'asis', comment = NA, message = F, echo = F} 
require(rCharts)
hair_eye_male <- s
subset(as.data.frame(HairEyeColor), Sex == "Male")
n1 <- nPlot(Freq ~ Hair, group = "Eye", data = hair_eye_male, type = "multiBarChart")
n1$print("chart3")

```
