### ISSUE TITLE
Equations in Latex not rendering

### ISSUE THREAD

**Issue by smartmediacorp** [ramnathv/slidify#268]
I just installed the latest development version of slidiy and slidifylibrary from Github.

Equation rendering in Latex appears broken.  I put a single line in a slide:

Test an equation `$A = 1+2$` with some text after it.

The resulting file, opened in a local browser,  displayed:

Test an equation `\(A = 1+2\)` with some text after it.

This is literally a "slash" followed by a "parenthesis" surrounding my equation.

All I did was:

```
author("mydeck")
# Then added equation to slide 1
slidify("index.Rmd")
# Then opened resulting index.html file in Firefox browser.
```

Thanks

**Comment by jiayiliu** [comment]
Hi @ramnathv ,
It is a wonderful package, however when i insert an inline latex, the symbol shows in the second line, instead of inline.  Do you know the cause?

Thanks
