### ISSUE TITLE
Slidify and RStudio presentations

### ISSUE THREAD

**Issue by stla** [ramnathv/slidify#278]
The new RStudio has a feature to create slides: http://www.rstudio.com/ide/docs/presentations/overview 
This looks like `slidify`, but is it really the same thing or not ?

**Comment by nvramamoorthy** [comment]
I am recently learning slidify. 
> slidify(index.Rmd) 
creates .md file but not .html file.

I am getting following message 

> slidify("index.Rmd")


processing file: index.Rmd
  |.................................................................| 100%
  ordinary text without R code


output file: index.md

Error in if (body$content == "") { : 
  missing value where TRUE/FALSE needed
> 

Please suggest solution.

**Comment by stla** [comment]
https://github.com/ramnathv/poirot/issues/32#issuecomment-105265360

**Comment by stla** [comment]
You can try to run the following code.

```
library(slidify)

parse_body <- function(body){
  html = ifelse(body != '', md2html(body), '')
  pat = '^(<h([0-9])>([^\n]*)</h[0-9]>)?\n*(.*)$'
  pat = regex(pat, dotall = TRUE, multiline = TRUE)
  body = setNames(as.list(str_match(html, pat)),
   c('html', 'header', 'level', 'title', 'content'))
  # body = modifyList(body, parse_content(body$content))
  # HACK: So that landslide h1's with no content are centered
  if (body$content == "" | is.na(body$content)){
  	body$content = NULL
  }
  if (body$header == "" | is.na(body$header)){
    body$header = NULL
  }
  return(body)
}
assignInNamespace("parse_body", parse_body, ns="slidify")

slidify("index.Rmd")
```

**Comment by nvramamoorthy** [comment]
Thank you for your  immediate reply .

I deleted and the index.html and libraries folder.

the again executed slidify("index.Rmd")

It worked nicely.

Please check the slides here 
http://nvramamoorthy.github.io/Coursera-Slidify-Project/

I wanted to add images into the pages.

If you have any suggestion please help me.

I will master Slidify  reading all documentation available.

Have Nice Day!
