### ISSUE TITLE
 '.Random.seed' not found when running runDeck() a second time 

### ISSUE THREAD

**Issue by stla** [ramnathv/slidify#290]
When Iaunch runDeck(), everything works very well. But if I stop the connection, and if I launch runDeck() again, I systematically get this error: 

```
Quitting from lines 17-28 (index.Rmd) 
Error in get(i, envir = from, inherits = FALSE) : 
  object '.Random.seed' not found
```

(17-28 corresponds to the first chunk)

**Comment by jjesusfilho** [comment]
I am having the same problem, I set cache=F but it still doesn't work.
