### ISSUE TITLE
"incomplete final line" warning with runDeck()

### ISSUE THREAD

**Issue by stla** [ramnathv/slidify#294]
I always get this warning when running `runDeck()`:

```
output file: index.md

Warning in readLines(doc, ...) :
  incomplete final line found on 'index.Rmd'
```

It does not cause any other problem but I'd like to get rid of it. What is the cause of this warning ?

**Comment by ptoche** [comment]
The space at the end of the line, it appears, can cause the problem. Thanks stla for pointing it out.
