### ISSUE TITLE
object 'opts_current' not found

### ISSUE THREAD

**Issue by ChriguK** [ramnathv/slidify#299]
Hi everyone

I just figured out how to publish slide decks on Github using slidify - and it is absolutely awesome!
Now I tried reproducing the NVD3 Plot Iframe example from rCharts. Unfortunately, I get an error message: "object 'opts_current' not found", and I do not know how to deal with this error. The code can be found here: https://github.com/ChriguK/testing3

Any help would be highly appreciated!

Greetings,
Christian

**Comment by ManuelZ** [comment]
Hi, I just had the same issue, loading knitr solved it. Using latest packages versions.
