### ISSUE TITLE
update reveal.js framework to allow 'data-background'

### ISSUE THREAD

**Issue by johnstantongeddes** [ramnathv/slidify#336]
The revealjs framework needs to be updated to the newest version which allows setting custom color background or images using the 'data-background' argument. In addition, the "section" line of the "slide.html" template should be updated:

    <section class='{{slide.class}}' data-state='{{slide.ds}}' id='{{slide.id}}' data-background='{{slide.background}}'> 

so that the data-background can be set within the index.Rmd file as such:

    --- .background "#007777"

See this question on [stackoverflow](http://stackoverflow.com/questions/21530742/slidify-set-background-with-reveal-js-framework/21532277?noredirect=1#comment32520556_21532277)

Thanks for the great tool and quick help!

**Comment by jonathan-g** [comment]
You can do this yourself.

Edit libraries/frameworks/revealjs/layouts/slide.html and libraries/frameworks/revealjs/layouts/vertical.html and edit the html tags to look something like this:

    ```<section class='{{slide.class}}' data-state='{{slide.ds}}' id='{{slide.id}}' data-background='{{slide.bg}}' data-transition='{{slide.dt}}' background-transition='{{slide.bt}}'>```

Then you can specify a slide like

    ---  bg:#007777 dt:slide bt:fade

to set the background, data transition, and background data transition.
