### ISSUE TITLE
Cannot visualize rCharts (Slidify)

### ISSUE THREAD

**Issue by tspeidel** [ramnathv/slidify#342]
OS: Ubuntu 13.10 x64
Rstudio: 0.98.501
R: 3.0.2

I'm using the presentation knitr markdown feature of Rstudio.  I'm having difficulties producing an rCharts plot.  I have followed Ramnath' suggestions from a similar post. I'm new to this, so I'm not entirely sure how to proceed. Below are the key chunks from the *.Rpres markdown file.

``` r requirements, echo =FALSE, results='hide', message=FALSE
require(rCharts)
require(devtools)
require(slidify)
require(slidifyLibraries)
##pkgs <- c("slidify", "slidifyLibraries", "rCharts")
##devtools::install_github(pkgs, "ramnathv", ref = "dev")
setwd("~/Documents/S/MD/")
```
# SLIDE

``` r ndv3plot1, results='asis', comment = NA, message = FALSE, echo = FALSE
require(rCharts)
n1 <- nPlot(mpg ~ wt, data = mtcars, type = 'scatterChart')
n1
```

The chart does not get visualized.  If I open the slidify presentation in Firefox, the Iframe complains that it cannot find the file:

Firefox can't find the file at /tmp/RtmpvP7aMJ/view2f57618a9e5c.dir/MD001_presentation-figure/ndv3plot1.html.

If I manually submit the rChart in the console, the Rstudio viewer does not display the chart, but the browser does.  I'm not really sure what's happening.

**Comment by cnicollet** [comment]
Hello, 

I'm trying to use your package slidify which is very cool, but I can't see my plots when using rCharts package.
**Below is the code I used:**

library(rCharts)
iris1 <- iris
names(iris1) <- gsub('\\.', '', names(iris1))
rPlot(SepalLength ~ SepalWidth | Species, color = 'Species', type = 'Point', data = iris1)

**Result:**
<iframe src=' figure/unnamed-chunk-2-1.html ' scrolling='no' frameBorder='0' seamless class='rChart nvd3 ' id=iframe- chart3fae4fb0f452 ></iframe> <style>iframe.rChart{ width: 100%; height: 400px;}</style>

I've already tried to save my code as you described above but, it opens a empty browser, nothing else.

Many thanks for your help!

**Comment by cnicollet** [comment]
Hello again, 
I think I just forgot to set ' results="asis" ' in the chunk option. I works fine now!
