### ISSUE TITLE
Cannot display fractions and power correctly

### ISSUE THREAD

**Issue by zhugejun** [ramnathv/slidify#389]
I want to put logistic regression expression on my slide, but for the power and fractions cannot display correctly. 

I believe I write in the right way. 
$x^{n}$
$p(t) = 1 / {1+e^{-t}} = \frac{e^t}{1+e^t}$

When I slidify, they all keep the same, not the equations.

**Comment by oskar-j** [comment]
Hi @zhugejun 

it's a LaTeX code. You have at least 2 options for showing it. One is using external service for automatic transcription to a .png file and embedding an img tag in your markdown

```
<img src="http://latex.codecogs.com/gif.latex?\dpi{300}&space;x^{n}" />
<img src="http://latex.codecogs.com/gif.latex?\dpi{300}&space;p(t)&space;=&space;1&space;/&space;{1&plus;e^{-t}}&space;=&space;\frac{e^t}{1&plus;e^t}" />
```

Second way is using mathjax, which I never tried, but you can read about it here:

[How to use MathJax in Slidify?](http://stackoverflow.com/questions/13830580/how-to-use-mathjax-in-slidify)
