### ISSUE TITLE
Slidify not available for R version 3.1.2

### ISSUE THREAD

**Issue by pseudouser** [ramnathv/slidify#405]
I get an error message that slidify is not available for the most recent version of R (I was able to install many other R Packages... it seems only slidify is stuck).
Is there a build in the pipeline I can look forward to... or must I switch to an older version of R...?
I'm on a machine running 64-bit Win 8.1 Pro.

**Comment by yosuke-takahashi** [comment]
Hi! ramnathv  your previous comment is good for me. I suceed to install slidify. Thank you!
* installing *source* package 'slidify' ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (slidify)
yosuke takahashi

**Comment by liznyamu** [comment]
Hi Ramnathv ...thanks to you i was able to install slidifysucessfully.

**Comment by Camrank1** [comment]
I got Error in loadNamespace(name) : there is no package called ‘devtools’

**Comment by sjagota** [comment]
yep looks like you would need to install devtools first:

install.packages("devtools")

and then:

pkgs <- c('ramnathv/slidifyLibraries', 'ramnathv/slidify')
devtools::install_github(pkgs)

Works fine after this.

- Thank you ramnathv

**Comment by irusin** [comment]
Thank you, ramnathv!

**Comment by abdusamed** [comment]
I'm trying to install slidfy on Rstudio in Ubuntu but getting issues.

> library(devtools)
> Error in library(devtools) : there is no package called ‘devtools’
> devtools::install_github
> Error in loadNamespace(name) : there is no package called ‘devtools’
> installed.packages("devtools")
>      Package LibPath Version Priority Depends Imports LinkingTo
>      Suggests Enhances License License_is_FOSS License_restricts_use
>      OS_type Archs MD5sum NeedsCompilation Built

My version

R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

**Comment by ramnathv** [comment]
Based on the error message, you don't seem to have the `devtools` package installed on your computer. Install it by running `install.packages("devtools")` and then install slidify.

**Comment by AkshataMirji** [comment]
Hi Ramnath
I tried installing slidify, but getting the below error message:
Downloading GitHub repo AkshuMirji/slidifyLibraries@master
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached

The version of R is 3.2.2

Kindly advise

**Comment by safferli** [comment]
You'll need to set your proxy, I'd wager. A

**Comment by hafumuen** [comment]
Hi Ramnath,
I tried to install slidify as followed,but was told that the request was deprecated.
library(devtools)
install_github('slidify', 'ramnathv')
install_github('slidifyLibraries', 'ramnathv')

I got:
skipping install for github remote, the SHA1 (1dd41a30) has not changed since last install.
  Use `force = TRUE` to force installation
Warning message:
Username parameter is deprecated. Please use ramnathv/slidify 

Skipping install for github remote, the SHA1 (dbd065f4) has not changed since last install.
  Use `force = TRUE` to force installation
Warning message:
Username parameter is deprecated. Please use ramnathv/slidifyLibraries 

Then what shall I do to get slidify?
Thank you so much

**Comment by salvalizarraga** [comment]
Thank you Ramnath!

**Comment by pachadotdev** [comment]
same error as @hafumuen 
my solution was 

```
pkgs <- c('ramnathv/slidifyLibraries', 'ramnathv/slidify')
devtools::install_github(pkgs, force = TRUE)
```

**Comment by RyanMAllen** [comment]
I tried to download slidify on R 3.3.3 and got the message
      package 'slidify' is not available (for R version 3.3.3)

Any ideas why? Is there a newer version of slidify (maybe slidify2?) like there was for ggplot (ggplot2)?

**Comment by luffy4258** [comment]
@pachamaltese's solution  works fine

**Comment by luffy4258** [comment]
THank you.
