### ISSUE TITLE
slidify no contents after publish

### ISSUE THREAD

**Issue by songlh15** [ramnathv/slidify#411]
Dr Vaidyanathan,

The slides I created works very well in my local machine and in the browsers. But after I publish to Rpub or dropbox, there are no slides showing up.  I am running windows 7 Rstudio Version 0.98.1102. 

I tried both in chrome and IE, but neither works. If I run the index.html in the default folder it works but if I copy to other folder like dropbox it stopped. 
Any Suggestions?

Thanks!

**Comment by ramnathv** [comment]
Are you using `mode: standalone` or `mode: selfcontained`?

**Comment by songlh15** [comment]
Thanks so much for your hint!  You saved my day! This is first time that I write all my presentation slides using Slidify!  Fantastic tools!

**Comment by ramnathv** [comment]
I am glad you find it useful. I am closing this issue. If you have other questions, feel free to open new issues.
