### ISSUE TITLE
Using the Bootstrap framework and the Bootstrap widget creates a confusing background

### ISSUE THREAD

**Issue by kferris10** [ramnathv/slidify#412]
For example, [this page](http://kferris10.github.io/bad-bootstrap/) is generated by using Slidify with this Rmd file

    ---
    framework   : bootstrap        
    widgets     : [bootstrap]            
    mode        : selfcontained 
    knit        : slidify::knit2slides
    ---
    
    ## An Example Bootstrap page
    
    Some text.
    
This [can be fixed](http://kferris10.github.io/good-bootstrap/) by adding some CSS to the Rmd file

    ---
    framework   : bootstrap        
    widgets     : [bootstrap]            
    mode        : selfcontained 
    knit        : slidify::knit2slides
    ---
    
    <style>
      body {
        background: white;
      }
    </style>
    
    ## An Example Bootstrap page
    
    Some text.
    
But would it be possible to change either the widget or the framework at all so that you don't initially see that black screen?

Here's my R session info if that helps.  I'm also using slidifyLibraries version 0.3.1

    > sessionInfo()
    R version 3.1.2 (2014-10-31)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    
    locale:
    [1] LC_COLLATE=English_United States.1252 
    [2] LC_CTYPE=English_United States.1252   
    [3] LC_MONETARY=English_United States.1252
    [4] LC_NUMERIC=C                          
    [5] LC_TIME=English_United States.1252    
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] slidify_0.4.5
    
    loaded via a namespace (and not attached):
    [1] evaluate_0.5.5 formatR_1.0    knitr_1.9      markdown_0.7.4
    [5] stringr_0.6.2  tools_3.1.2    whisker_0.3-2  yaml_2.1.13

**Comment by ramnathv** [comment]
The trouble is that the `bootstrap` widget might be used with other frameworks and people expect bootstrap to work in certain way. So I would prefer that the user add css classes to overrule behavior in a transparent way like you have done, as opposed to pushing a fix.

**Comment by kferris10** [comment]
Fair enough.  I just wanted to bring it to your attention in case you hadn't seen it before.

Great job on Slidify by the way!  I really enjoy using it.

**Comment by ramnathv** [comment]
Thanks @kferris10.
