### ISSUE TITLE
How to use dygraphs and DT in slidify?

### ISSUE THREAD

**Issue by jroberayalas** [ramnathv/slidify#414]
Hi! I'm trying to use the packages [DT](http://rstudio.github.io/DT/) and [dygraphs](http://rstudio.github.io/dygraphs/) into my slidify presentation in R. However, it seems it's not as straightforward as I thought. So far what I get is an output that looks like this:

![captura de pantalla 2015-03-12 a la s 17 26 00]
(https://cloud.githubusercontent.com/assets/8128586/6623755/e4b605e2-c8dc-11e4-96b8-b7ff4df89146.jpg)

Is there any extra command I need to add in order to use the htmlwidgets produced by the datatable() and dygraphs() commands?

Thanks!

**Comment by arturochian** [comment]
It's a slidify issue related to html widgets (I asked before with DT https://github.com/rstudio/DT/issues/9 ). 
Slidily is so awesome and its integration with htmlwidget would be really  "cRantastics"! :smile:  .
I forget reporting this issue to @ramnathv. 

Let me know if you solve this issue.

**Comment by ramnathv** [comment]
Slidify needs to implement some fundamental changes to let `htmlwidgets` place nicely with it. It is on my list of things to do, but thanks for filing an issue.

**Comment by jroberayalas** [comment]
Thanks for your answer @ramnathv. Hope these changes come in the future. I'm a big fan of slidify!

**Comment by joseah** [comment]
Asking something related to this in DT https://github.com/rstudio/DT/issues/40
You can do this:
```
dynamic_table <- DT::datatable(x)
DT::saveWidget(dynamic_table, 'example.html')
cat('<iframe src="example.html" STYLE="width:100%;height:125%"> </iframe>')
```
I don't like mixing html code within slidify markdown, but it works. Hope this could be useful.

**Comment by mbh038** [comment]
I am having the same problem as @jroberayalas in Slidify and R presentation with leaflet.

**Comment by embiuw** [comment]
Hi,
This thread goes back a few years now. Just wondering if you've managed to make any progress on linking htmlwidgets and slidify? Slidify is fantastic, but I would really like to embed dygraphs in my presentations.
