### ISSUE TITLE
index.html isn't using most up to date data

### ISSUE THREAD

**Issue by bbritten** [ramnathv/slidify#415]
I'm working on a presentation and it requires a lot of iterations in terms of moving code/output to different slides etc. One of the things I'm doing involves using RSQLite and connecting to a database that's saved in my Slidify directory. The issue is that when I run slidify('index.Rmd') after tweaking the database in R, the new presentation doesn't reflect the new data. As a specific example: I have a database called Crimes.db and in one of my iterations of slidify('index.Rmd') I created a table in Crimes.db called Totals. The next time I loaded index.html I got an error saying Totals already existed. So I removed the table in R and then added code to do the same in my index.Rmd file. However, every time I load index.html, I get the same error. 

In addition, I deleted the entire database from my directory to see what would happen and I got what I expected: running index.html (after re-running slidify('index.Rmd')) brought up the presentation with the same error: table Totals already exists. Even more weird is that it seemed to run the code in the previous steps, including querying a database that no longer exists.

Does slidify('index.Rmd') not actually update the index.html file? If not, how do I go about this? If it's supposed to update it, why is it not working?

**Comment by ramnathv** [comment]
Have you tried deleting the `.cache` folder that `knitr` creates? Most errors of this kind are usually due to the cache interfering with the updates. You can delete the cache by running `system('rm -rf .cache')`.

**Comment by bbritten** [comment]
I figured it was going to be something simple. This did the trick and everything is working fine now. Truly an awesome product you have here with a large amount of applications. Keep up the good work!

**Comment by ramnathv** [comment]
Thanks. I am closing this issue. Feel free to reopen/post a new one if you have further problems.
