### ISSUE TITLE
flowtime warning

### ISSUE THREAD

**Issue by treysp** [ramnathv/slidify#416]
I'm consistently getting the following warning when I `slidify()` a flowtime presentation. The HTML presentation is successfully created and correctly rendered in the browser. 
```
Warning message:
In readLines(doc, ...) :
  incomplete final line found on 'libraries/frameworks/flowtime/layouts/vertical.html'
```
The warning message does not appear if I add a newline to the end of the "vertical.html" file. I'm on Windows, so this may be an OS-specific CR/EOL issue.

**Comment by ramnathv** [comment]
It is just a warning that `readLines` gives. You can ignore it.
