### ISSUE TITLE
Global assets folder for multiple decks

### ISSUE THREAD

**Issue by jvcasill** [ramnathv/slidify#421]
I am trying to get multiple decks in a master directory to point to a global assets folder. I have outlined the issue [here](http://stackoverflow.com/questions/29826620/using-global-assets-for-multiple-decks-in-slidify). In short, I would like to change the structure of the directory from this...

    - master
        - deck1
            - index.Rmd
            - assets
            - libraries
        - deck2
            - index.Rmd
            - assets
            - libraries

To this...

    - master
        - assets
        - libraries
        - deck1
            - index.Rmd
        - deck2
            - index.Rmd

Is this currently possible in slidify? Thank you.

**Comment by ramnathv** [comment]
Yes. It is possible. You can look at this repo as an example

https://github.com/slidify/lectureSite

The key is to use the following in your YAML front matter to explicitly specify relative paths to the `libraries` and `assets` folder

```
---
...
url: {lib: ../libraries, assets: ../assets}
...
---
```

**Comment by jvcasill** [comment]
This is perfect. Worked like a charm. Thank you for your time and hard work. If you'd like, copy and paste this as an answer to my question referenced above on stackoverflow. If not, I will answer and link to your response here.

**Comment by ramnathv** [comment]
@jvcasill Feel free to answer the question on SO and link to my response here.
