### ISSUE TITLE
view_deck() returns error 

### ISSUE THREAD

**Issue by sux13** [ramnathv/slidify#428]
`Error in FUN(X[[i]], ...) : no such symbol rs_viewer` is returned every time I tried to view the deck

Below is my session Info

```
R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] slidify_0.4.5

loaded via a namespace (and not attached):
[1] magrittr_1.5      markdown_0.7.7    tools_3.2.0       whisker_0.3-2    
[5] yaml_2.1.13       rstudio_0.98.1103 stringi_0.4-1     knitr_1.10.5     
[9] stringr_1.0.0
```

**Comment by ramnathv** [comment]
Are you trying to use `view_deck` inside of RStudio or from the regular R GUI?

**Comment by sux13** [comment]
Regular R GUI

**Comment by ramnathv** [comment]
The `view_deck` function is to view the slide deck in the RStudio Viewer. So it will not work in the R GUI. All you need to do then is to open the `index.html` file in your browser either manually or using `browseURL('index.html')`

**Comment by sux13** [comment]
Thanks!

**Comment by sux13** [comment]
Actually on second thought, I was able to run `view_deck()` directly from R GUI somehow before. It automatically set it up on local host and I was able to run the presentation directly from it. I'm not sure what I changed and somehow I can't run `view_deck()` anymore.

The only reason I can't just use browseURL is because the speaker notes don't work on just a HTML page, but has to be set up on a server. Any ideas?

**Comment by sux13** [comment]
Nevermind. I was using `runDeck()`. Sorry about that

**Comment by ramnathv** [comment]
No problems. It seems like a good idea to enhance `view_deck` so that it works in the R GUI as well.

**Comment by sux13** [comment]
I also want to thank you for being so responsive and all of your hardwork on slidify. With slidify and reveal.js, I have completely replaced Excel/PPT, and Numbers/Keynote. It is absolutely fantastic!

**Comment by ramnathv** [comment]
Thanks.
