### ISSUE TITLE
RCurl error

### ISSUE THREAD

**Issue by desmondpatel** [ramnathv/slidify#434]
Hi Ramnath,
I have made index.html file using slidify.
I also have .RProfile file containing the single line options(rpubs.upload.method = "internal") in the same folder.
When I run the command publish(title = 'mytitle', 'index.html', host = 'rpubs') from this folder, it gives me the following error:
Error in RCurl::curlOptions(url, cainfo = sslpath) : 
  unnamed curl option(s): https://api.rpubs.com/api/v1/document
Help required.
Kind regards,
Desmond

**Comment by ramnathv** [comment]
This is NOT a slidify issue, and relates to your internet proxy settings. I would recommend posting this on a forum like [StackOverflow](http://www.stackoverflow.com).

**Comment by desmondpatel** [comment]
OK thanks

**Comment by littlefoxhome** [comment]
I have the same issue.... It can be fixed. Need choose right R version.
