### ISSUE TITLE
Embedding simpleNetwork Plot From networkD3 Package Not Rendering

### ISSUE THREAD

**Issue by theRanalyst** [ramnathv/slidify#435]
I've tried a slew of different things and cannot get a simpleNetwork plot to render in a Slidify deck when using runDeck(). I have added "ext_widgets : {networkD3: [htmlwidgets]}", "ext_widgets : {networkD3: [htmlwidgets/lib]}", "ext_widgets : {networkD3: [htmlwidgets/lib/d3-3.5.2]}" and all combinations there of to my yaml, but nothing seems to work. I have also added simpleNetwork to my widgets line. I've tried using slidifyUI with htmlOuput, simpleNetworkOutput, or tags$div(id='networkGraph' class='shiny-html-output simpleNetwork networkD3') in the mainPanel( ) section. Am I missing something with regard to htmlwidgets or Slidify?

**Comment by ramnathv** [comment]
`htmlwidgets` integration for `slidify` is still work-in-progress.
