### ISSUE TITLE
Slidify and Shiny controls

### ISSUE THREAD

**Issue by datalotpot786** [ramnathv/slidify#440]
Ramnath, It appears shiny controls in slidify works only with runDeck() command. This requires R studio and the Rmd to be running. 
Is it possible to have shiny control as part of html file? This way we can present the decks without R. 

Also are there any plans in rCharts with drill down capabilities?

Thanks
Sandeep

**Comment by ramnathv** [comment]
@datalotpot786 Shiny requires R to be running. That is how it is designed. So you cannot present decks containing shiny components without R.
