### ISSUE TITLE
I am struggling with slidify error 

### ISSUE THREAD

**Issue by kumar-velugula** [ramnathv/slidify#442]
Error in if (body$content == "") { : 
  missing value where TRUE/FALSE needed
I have been struggling with this and couldn't find any viable solution. Please help!

I am running R Studio v.0.98.1103  on Mac

**Comment by ramnathv** [comment]
See this [thread](https://github.com/ramnathv/slidify/issues/430).

**Comment by kumar-velugula** [comment]
Thanks Ram, I have installed as per and it at last worked ...weird it wasn't working with first few attempts of the same and crashed the R studio.
install.packages('stringr')
devtools::install_github('muschellij2/slidify')

**Comment by ramnathv** [comment]
This happens when you try to install packages that are already loaded in your session. The best way to avoid this is to make sure that you restart your R session before doing any package installations/updates.
