### ISSUE TITLE
ggplot2 not displaying with slidify and shiny

### ISSUE THREAD

**Issue by datalotpot786** [ramnathv/slidify#444]
Sharing snippet of my  index.Rmd code as well as server.R code. Basically I have data frame loaded in slidify with rows. I have added Shiny Input control and trying to use the input as filter on data frame. In plotOutput I am calling ggplot2 function which is located in server.R. Issue is that it does not show the ggplot in slidify. Please let me know what am I missing? I have also included initial portion of index.Rmd

index.Rmd
---
title       : Data Mining with Word Cloud
subtitle    : Word Cloud association of terms
author      : Sandeep Patwardhan
job         :
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : solarized_light      #
widgets     : [bootstrap, shiny, interactive, polycharts, ggplot2]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---
 
## Data Preperation
 
```{r, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}
read_chunk('app/global.R');read_chunk('app/server.R')
```
 
--- &twocol w1:50% w2:50%
 
### Frequent Words and Cluster Dendogram
 
*** =left
```{r echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
 
slidifyUI(
  sidebarPanel(
    selectInput(inputId="freq",label="Frequent Words:",choices=c(5,10,15,20,25),selected=15)
  ),
  mainPanel(
    #showOutput('wordfrq', 'polycharts')
    plotOutput('wordfrq')
  )
)
 
```
 
server.R
require(ggplot2)
shinyServer(function(input,output){
  output$wordfrq <- renderPlot({
    df1 = head(df,input$freq)
    colourCount = input$freq
    p1 = ggplot(df1, aes(x = reorder(word, -freq), y = freq, ymax=max(freq), fill=getPalette(colourCount))) +
      geom_bar(stat = 'identity', position=position_dodge(0.7), size=0.3, width=0.3) +
      theme(panel.grid=element_blank()) + theme_grey(base_size = 12) +
      ggtitle("Wordcloud - Most Frequent Words") + theme(plot.title = element_text(lineheight=0.8, size=12, face="bold")) +
      xlab("Word") + ylab("Frequency") + coord_flip() + theme(legend.position='none')
    print(p1)
  })
})

**Comment by datalotpot786** [comment]
Ramnath, Please let me know ggplot2 can work with above combinations?

**Comment by ramnathv** [comment]
`ggplot2` should work with `slidify`. I think the trouble is the shiny integration, which was always a little hacky. I am approaching this issue from scratch, to integrate shiny documents into slidify, rather than hacking on the hack.
