### ISSUE TITLE
Please share example of googlevis with shiny control with Slidify

### ISSUE THREAD

**Issue by datalotpot786** [ramnathv/slidify#446]
Ramnath,

Can you please example of using googlevis along with shiny in slidify. Basically I would like to have some Input Control with Shiny and then using these inputs with googleVis package to show output in slidify presentations.

Thanks

Sandeep

**Comment by datalotpot786** [comment]
Ramnath, Please let me know the example of googlevis with shiny/slidify

**Comment by ramnathv** [comment]
Take a look at any examples that use `runDeck` which is how slidify operates with shiny currently. I will try to put together a specific example, but it might be a few weeks before I can get to that.
