### ISSUE TITLE
rChart issue

### ISSUE THREAD

**Issue by sabrineZhr** [ramnathv/slidify#448]
Hi,
I'm trying to display the result of  a lineChart but i have this issue 
<img width="1269" alt="capture d ecran 2015-07-09 a 15 15 37" src="https://cloud.githubusercontent.com/assets/8748817/8597530/da7afe60-264d-11e5-88c0-e73065871891.png">

this is my R function

library(RMySQL)
library(rCharts)
library(ggplot2)
mydb = dbConnect(MySQL(), user='root',     password='root',dbname='test', host='192.168.0.164')
loginTest = dbGetQuery(mydb, "SELECT date, param1  FROM test.core_event where code = 'LOGIN';")
loginTestYear <- as.data.frame(strftime(loginTest$date, "%y"),loginTest$param1)
colnames(loginTestYear)[1] <- "year"
p <- nPlot(~ year , data = loginTestYear , type = 'lineChart')
p$save("output.html", cdn = TRUE)

this is my script 
myApp.controller('MainCtrl', function($scope, $http){
   
   $scope.makeChart = function(){
     $("#output").attr('src', '')
        $("#loading").show()
    onsubmit="return false;"
        var req = ocpu.call("rChart", {
          
     }, function(session){
       $("#loading").hide()
       $("#output").attr('src', session.getLoc() + "output.html");  
       $scope.$apply(function(){
         $scope.dnlink = session.getLoc() + "output.html"
       })
     }).fail(function(text){
      alert("Error: " + req.responseText);
     });  }

and this is how i call the iframe
<iframe id='output' seamless scrolling = "no" frameborder = "0"
         allowTransparency = "true"></iframe>
Can you help me

**Comment by sabrineZhr** [comment]
I changed  "output.html" to  "files/output.html" in my javascript and it worked what does this folder (files) refer to ?

**Comment by ramnathv** [comment]
I suspect it must be the default path assigned to all files that are being referred to.
