### ISSUE TITLE
Publishing slidify to github, object not found 

### ISSUE THREAD

**Issue by moptop** [ramnathv/slidify#451]
I am trying to publish a slidify deck to github. I believe I followed all of the documentation correctly. I created an empty repo called app_pitch (https://github.com/moptop/app_pitch). When I run:

publish_github(moptop, app_pitch)

in RStudio from my slidify html file directory, I get:

Error in message("Publishing deck to ", username, "/", repo) : object 'app_pitch' not found.

In an attempt to solve the problem I generated an ssh key and successfully set up ssh access to github. But this made no difference, I got the same error when running the same publish code.

I updated R and Rstudio to the most recent versions, and I am using Windows 8.

I am fairly new to github, and it's my first time using slidify, so hopefully the answer is an easy one. Thanks so much for any suggestions.

**Comment by ramnathv** [comment]
You need to run `publish_github("moptop", "app_pitch")`. The error message indicates what went wrong.

**Comment by moptop** [comment]
Thank you, the tutorial I used didn't show quotes, my apologies.
