### ISSUE TITLE
Alignment of text 

### ISSUE THREAD

**Issue by fintzij** [ramnathv/slidify#452]
Hello,

I am wondering if it is possible to left-align all of the slides in the reveal.js framework so that they have the same margin. Transitions from one slide to the next are distracting when the margin changes due to text and lists being centered based on the number of characters per line within different slides.

Thanks

**Comment by jonathan-g** [comment]
Add the following to the end of libraries/frameworks/revealjs/partials/head.html:

    <style>
        .reveal .slides,
        .notransform .reveal .slides,
        .reveal .overlay.overlay-help .viewport .viewport-inner {
            text-align: left;
        }
    </style>

If you want to do this selectively, on a per-slide basis, then you can just make a CSS class (I call it leftslide) and change the above style section to

    <style>
        .leftslide .reaveal .slides,
        .leftslide .notransform .reveal .slides,
        .leftslide .reveal .overlay.overlay-help .viewport .viewport-inner {
            text-align: left;
        }
    </style>
and start your slide with `---- .leftslide` or `*** .leftslide` in your Rmd file.

**Comment by ramnathv** [comment]
That sounds about right. @jonathan-g thanks for doing this. Would you mind creating a wiki page outlining your solution?

**Comment by fintzij** [comment]
Thank you for the help!
