### ISSUE TITLE
Slidify does not Plots

### ISSUE THREAD

**Issue by Tinausa** [ramnathv/slidify#453]
I created an rmd file and ran 
slidify("Project/index.rmd")
browseURL("Project/index.html")

And I can see plots - these are created within the rmd file by some R code.

When I push it to rpubs, it does not show the plots. The slides do show, but instead of plots, there is text 
plot of chunk unnamed-chunk-1

What am I doing wrong? Any help would be greatly appreciated. 

I have updated to the latest R, RStudio and all the packages, running on Windows 10.

Thanks much in advance.

**Comment by ramnathv** [comment]
Slidify does not embed the plots directly in the resulting html. That is the reason you don't see the plots in Rpubs. If you push the entire folder to github, everything will work.
