### ISSUE TITLE
Duplication of header when adding custom slide background

### ISSUE THREAD

**Issue by sachinsancheti1** [ramnathv/slidify#454]
I used a solution you gave on [stackoverflow](http://stackoverflow.com/questions/22567127/slidify-how-to-customize-a-slide-background) to create a custom picture background, but in the process I found that the header of the slide duplicates the header. The resulting slide gives me 2 headers in the file, one in the hgroup tag, and another h2 within the article tag. I am guessing there is a bug here.

<slide class="current" id="slide-3" style="background:" .="" assets="" img="" picture1.png";"="" data-slide-num="5" data-total-slides="16">
  <hgroup>
    <h2>Header</h2>
  </hgroup>
  <article data-timings="">
    
<h2>Header</h2>

<p>Losen ipsum..</p>

**Comment by ramnathv** [comment]
Your use of slide attributes does not seem correct, since it is producing invalid attributes. Can you post your Rmd source?

**Comment by sachinsancheti1** [comment]
Hi...i have a [git repo](https://github.com/sachinsancheti1/slidifyGokulGardens) for it. I think the most relevant files would be the (Rmd file)[https://github.com/sachinsancheti1/slidifyGokulGardens/blob/gh-pages/index.Rmd] and the (layout file)[https://github.com/sachinsancheti1/slidifyGokulGardens/blob/gh-pages/assets/layouts/custbg.html]

**Comment by ramnathv** [comment]
I don't see any duplication of header in your html files.

**Comment by sachinsancheti1** [comment]
Thanks for the quick response. I'm very sorry, I tweaked with the html file earlier to showcase it. I have just rerun the code. 
![duplicates](https://cloud.githubusercontent.com/assets/6279770/9527140/bf1da58a-4d0a-11e5-838d-5cbd296b32bf.png)

**Comment by ramnathv** [comment]
You need to use `{{{ slide.content }}}` in your `custbg` template. It is a template that inherits from the default `slide` template. `{{{ slide.html }}}` contains all the html on the page and so using that leads to duplication of the header. `{{{ slide.content }}}` only replaces the content, leaving the header as is. You will find more information on slide level properties [here](https://github.com/ramnathv/slidify/wiki/Properties).
