### ISSUE TITLE
Mustache template problems with boolean parameters

### ISSUE THREAD

**Issue by jonathan-g** [ramnathv/slidify#455]
Two mustache/whisker questions:
1. If my yaml header in the .Rmd has something like
   
   ```
   revealjs:
       foo: true
   ```
   
   and my template has something `{{page.foo}}`, it is translated as `TRUE`, not `true`. This breaks javascript that is expecting `true` and doesn't know what `TRUE` is.
2. Is there a way to get the conditional substitution in the mustache templates to tell the difference between setting a parameter to `false` and not setting it?
   
   I would like to have a template that uses the setting in `page` if it's set in the page yaml header, but use a value that I read in from site.yml if the page's yaml header doesn't specify anything. I would do something like this:
   
   ```
     {{#page.foo}}
     {{page.foo}}
     {{/page.foo}
     {{^page.foo}}
     {{#site.foo}}
     {{site.foo}}
     {{/site.foo}}
     {{/page.foo}}
   ```
   
   This works for strings and numbers, but if page.foo is a boolean value, then if site.yml has `foo: true` and index.Rmd has `foo: false` in the yaml header, I get `{{site.foo}}` (that is, `true`), not `false`

**Comment by ramnathv** [comment]
Here are some quick responses.
1. The YAML parsing is done by the `yaml` package which will treat `true` as `TRUE`. The easiest thing to make this work on the javascript side is to use `page.foo === "TRUE"`, or even better write a function that will return `true` when the input is `TRUE`.
2. This is an interesting question. My initial thought is that I don't think this is possible with `whisker`. Let me see if there are any workarounds I can come up with.

**Comment by jonathan-g** [comment]
Thanks for the suggestion on #1. That sounds like it will work for me.

On #2, maybe it's not possible with whisker, so an alternative that might work for me would be to create a separate variable `foobar` (as in the complement of `foo`) and set `foobar : true` to accomplish what I had wanted to do by setting `foo : false`

```
{{#page.foo}}
{{page.foo}}
{{/page.foo}
{{^page.foo}}
{{#page.foobar}}
false
{{/page.foobar}}
{{^page.foobar}}
{{#site.foo}}
{{site.foo}}
{{/site.foo}}
{{/page.foobar}}
{{/page.foo}}
```
