### ISSUE TITLE
Changing font size for slides

### ISSUE THREAD

**Issue by johnsonzhj** [ramnathv/slidify#456]
I found slidify appealing and want to use it to present a R course, here I have a question, how I can increase the font size of the bullets as in a example list below. I saw the previous issue on this topic you've answered and have tried, seems not solved the problem. Can you try to clarify this? Thanks.

```
##  Contents
>- 1. a brief introduction of R
>- 2. Installment and interface
>- 3. basics of R
```

**Comment by ramnathv** [comment]
If you want to increase the font size for all incremental bullets, you can override it using CSS. So, add this to your slide deck

``` css
<style>
article li.build {
  font-size: 16px;
}
</style>
```

To know what CSS to overrride, you can inspect the DOM using Chrome. For more details, see [this article](https://developer.chrome.com/devtools/docs/dom-and-styles).

**Comment by johnsonzhj** [comment]
Thanks!

Qiang Shen,PhD
Neuromanagement Lab,
Department of Management of Science and Engineering,
School of Management,
Research assistant professor,
Zhejiang University

**Comment by jonathan-g** [comment]
FWIW, I sometimes just want to change font size on some slides, so I made some css classes:

```
.ninety {
  font-size: 90%;
   }

.eightyfive {
   font-size: 85%;
   }
```

and so forth. Then when I want to change the size of a slide, in my .Rmd file I just put something like

```
--- .ninety
## Smaller slide

All the fonts on this slide are 90% of the normal size.
```

You can do the same kinds of things to enlarge fonts on a slide-by-slide basis. The ease with which you can attach multiple css classes to individual slides in slidify is enormously powerful for styling things.

**Comment by ramnathv** [comment]
That's a great tip @jonathan-g. Define `classes` and use them when you want styles to apply across slides. Note that slidify supports the concept of templates that allow you to do more than what styles let you do.

**Comment by arvchi** [comment]
Trying to understand css classes, but don't know where and how to define classes. For instance, where do I input the code supplied by jonathan-g?

```
.ninety {
  font-size: 90%;
   }

.eightyfive {
   font-size: 85%;
   }

```

@jonathan-g 

Thank you in advance!

**Comment by ramnathv** [comment]
You can define these in your Rmd file between style tags. So

``` html
<style>
.ninety {
   font-size: 90%;
}
</style>
```

**Comment by drkamarul** [comment]
Hi, 

I am very new to slidify and i know next to nothing about CSS. But I have found slidify very interesting and useful for me. My questions are related to the previous questions and I wish someone can help me.

Let us say I have these in my preamble and the first 2 slides. Slide no 2 has the R code chunk. 

```

---
title:
subtitle:
author:

---

## slide 1

AA
---

## slide 2

BB

```{r}
1 + 1 

```



Q1) where do I place the  <style>? above or below the preamble? For example, if I have <style> written as below 

```
<style>
.ninety {
   font-size: 90%;
}
</style>
```
2) How can I make the fonts for the slides let say at 24px and the fonts for the R code chunks and their outputs smaller like 18px?

Best wishes,
Kamarul
Universiti Sains Malaysia

**Comment by drkamarul** [comment]
I found this is helpful for changing the overall font size https://github.com/ramnathv/slidifyLibraries/blob/master/inst/libraries/frameworks/io2012/css/slidify.css#L23. 

But I am still looking for ways to edit the font size for just the R code chunks and their outputs.

**Comment by patarol** [comment]
> I found this is helpful for changing the overall font size https://github.com/ramnathv/slidifyLibraries/blob/master/inst/libraries/frameworks/io2012/css/slidify.css#L23.
> 
> But I am still looking for ways to edit the font size for just the R code chunks and their outputs.

In my case, I did something like:

```
---
title       : Title
author      : author
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
# deckjs:
#    theme: web-2.0
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : solarized_dark      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

<style>
article p {
  font-size: 16px;
}
article code {
  font-size: 14px;
}

</style>

## Slide 1
```
