### ISSUE TITLE
Tutorial command publish(user= USER, repo= REPO) publishing on github.com, not github.io

### ISSUE THREAD

**Issue by abdusamed** [ramnathv/slidify#457]
It's creating the sample or preview version of the HTML on github.com domain. Was following the tutorial mentioned on homepage of ramnathv/slidify

Running Rstudio on a Linux machine

**Comment by ramnathv** [comment]
Anything pushed to the `gh-pages` branch of a repo on the `github.com` domain, will appear in the `github.io` domain. So this should not be causing any issues.

**Comment by denkorzh** [comment]
@ramnathv actually  the command `publish` seems not to send the file to github. As says the webpage which opens after applying `publish` method, the presentation can't be sent to github.com

**Comment by ramnathv** [comment]
Can you specify the exact set of steps that you followed and the error message you got?

**Comment by denkorzh** [comment]
1. I created repo [denkorzh/psychology](https://github.com/denkorzh/psychology)
2. Launched automatic page generator - it created [this page](http://denkorzh.github.io/psychology/)
3. I created a test slidify presentation and applied `publish(user = "denkorzh", repo = "psychology")`. the result was following:

> Initializing Git Repo
> Checking out gh-pages branch...
> Adding .nojekyll to repo
> Publishing deck to denkorzh/psychology
> You can now view your slide deck at http://denkorzh.github.com/psychology
> Warning messages:
> 1: running command 'git init' had status 127 
> 2: running command 'git commit --allow-empty -m 'Initial Commit'' had status 127 
> 3: running command 'git checkout -b gh-pages' had status 127 
> 4: running command 'git add .' had status 127 
> 5: running command 'git commit -a -m "publishing deck"' had status 127 
> 6: running command 'git push git@github.com:denkorzh/psychology gh-pages' had status 127 

The presentation didn't appear

**Comment by bhaskargvb** [comment]
Hi Ramnath,
I am also facing the same issue. Can you please help me to resolve.

Thanks,
Bhaskar

**Comment by ramnathv** [comment]
See [this](https://github.com/ramnathv/slidify/issues/386)

**Comment by bhaskargvb** [comment]
Thank you for responding Ramnath. I tried the commands in below link through gitbash and could successfully publish:
http://stackoverflow.com/questions/23145621/how-to-publish-pages-on-github
