### ISSUE TITLE
Slidify not working with rcharts  and gooleVis graphs

### ISSUE THREAD

**Issue by Gunratan** [ramnathv/slidify#464]
I found below issues while addng graphs in slidify presentation using rcharts and googleVis:
- rCharts - graphs are not generating in presentation.
- googleVis - graphs are opening in new separate browser tab instead of embedding into slidify presentation.

Below code:
## rCharts example

``` r ichart, results = 'asis', echo = T
library(rCharts)
data(economics, package = "ggplot2")
econ <- transform(economics, date = as.character(date))
m1 <- mPlot(x = "date", y = c("psavert", "uempmed"), type = "Line", data = econ)
m1$set(pointSize = 0, lineWidth = 1)
m1$print("chart1")
```

---
## googleVis- Motion chart example

``` r motionchartcode, results='asis'
library(googleVis)
options(gvis.plot.tag="chart")
plot(gvisMotionChart(Fruits, "Fruit", "Year",
                     options=list(width=600, height=400)))
```

**Comment by ramnathv** [comment]
For `rmarkdown`, you need to use `m1$show('iframesrc')` instead of `m1$print`. If you search the issues page, you will find more details.

**Comment by Gunratan** [comment]
I am using it in slidify 

---

title       : Visualisation with googleVis & rCharts
subtitle    : 
author      : 
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}

## mode        : selfcontained # {standalone, draft}

**Comment by ramnathv** [comment]
You will need the same for `slidify` as well. For `googleVis` check out the docs to see how to output just the javascript and html instead of opening a new browser. I have done it before, but don't remember the details.

**Comment by Gunratan** [comment]
I changed print() to show(), but still it is not working. Below is my simple code for two slides:

[presentation.txt](https://github.com/ramnathv/slidify/files/49974/presentation.txt)

**Comment by Gunratan** [comment]
Sorry, my mistake. I am now able to embed rcharts in slidify presentation, but there is still problem with googleVis charts. Please suggest.

**Comment by Gunratan** [comment]
I got the solution for googleVis problem. Flash Player setting was not allowing me to depict the googleVis graphs in slidify. I followed the instruction from  

https://cran.r-project.org/web/packages/googleVis/vignettes/googleVis.pdf
2.4 Displaying gvis objects locally . . . . . . . . . . . . . . . . . . . . 16

 and it is working now.

Thank you Ramanathan for your great package.

**Comment by ramnathv** [comment]
You are welcome.

**Comment by imanojkumar** [comment]
May be this could help you:
https://stackoverflow.com/a/46874866/8814173

**Comment by takje** [comment]
Hi professor,

I've been reproducing your code to make up a slidify presentation, rChart works but not gvismotionchart. 
I've tried runDeck(), the codes don't run when I used the runcode button. 
I've opened the html with Microsoft Edge, the same thing happened.
I've used Chrome to open the html, it gets error: connection to open cpu failed. 

Can you help me out? 

Unfortunately, I'm not a computer person so I don't understand many technical terms, thank you.

Kind regards,
Tak
