### ISSUE TITLE
Layout custom parameters are not processed

### ISSUE THREAD

**Issue by slavakx** [ramnathv/slidify#465]
I saw a similar issue but it wasn't commented. I created my own layout and try to pass custom key:value parameters into it. It seems that they are completely ignored. Is there any solution to this issue?

**Comment by ramnathv** [comment]
Can you provide a reproducible example? It is hard to provide a solution otherwise.

**Comment by slavakx** [comment]
index.Rmd:

---

title       : 
subtitle    : 
author      : 
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
--- &slide_logo mylogo:'http://icons.iconarchive.com/icons/mazenl77/I-like-buttons-3a/128/Cute-Ball-Go-icon.png'

## Read-And-Delete
1. Edit YAML front matter
2. Write using R Markdown
3. Use an empty line followed by three dashes to separate slides!

**Comment by slavakx** [comment]
The layout file is on the picture: 
![slide_logo](https://cloud.githubusercontent.com/assets/6716523/11722691/83e98738-9f6a-11e5-9fd6-cdd7dbfc711e.PNG)

**Comment by slavakx** [comment]
So I just subtitute a parameter for an icon...

**Comment by ramnathv** [comment]
You need to use `{{{ slide.mylogo }}}` instead of `{{{ mylogo }}}`

**Comment by slavakx** [comment]
Yes. Solved. Thanks!
