### ISSUE TITLE
rmarkdown generated img width in percentage?

### ISSUE THREAD

**Issue by wieling** [ramnathv/slidify#467]
I'm very happy with slidify. However, when I go from widescreen to non-widescreen, my text scales (as I've used custom css for this purpose). External images also scale, as I've indicated width=X% in the <img> tag. However, the images which are being generated in R (in svg) have a fixed-width. Would it be possible to allow the width=X% option in the <img> tag there as well? Or use another option to allow these images to scale going from widescreen to non-widescreen. Now I have to make the images smaller, in order for them to fit in the non-widescreen display, which is less than ideal.

**Comment by ramnathv** [comment]
Markdown syntax does not permit adding attributes to images. If you want to specify widths, you can always fall back to html.

``` html
<img src='myimage.png' width='100%' />
```
