### ISSUE TITLE
Highlight code?

### ISSUE THREAD

**Issue by wieling** [ramnathv/slidify#468]
As I'm using slidify to generate my teaching slides, I would very much like to highlight some specific parts of my code (e.g., a new parameter which was added to a function, etc.). I could imagine that I surround the parts which I want to highlight by some kind of marker (such as '@'). Would this be possible within slidify?

**Comment by ramnathv** [comment]
This would have to be handled by a highlighter. I don't think `prettify` or `highlightjs` has this feature. If you find a highlighter that does this, or an extension, let me know and I can point you on how to integrate it with slidify.
