### ISSUE TITLE
Unable knit slidify

### ISSUE THREAD

**Issue by englianhu** [ramnathv/slidify#475]
I am trying to knit a created slidify file but the output has not execute any r codes.
![capture](https://cloud.githubusercontent.com/assets/7227582/12387810/6707717c-be12-11e5-8ddf-491b7beeacae.jpg)

and then I tried to post to rPubs but there has only blank page. Kindly assist
http://rpubs.com/englianhu/slidify-test

**Comment by ramnathv** [comment]
The YAML front matter is left untouched by slidify. So, this is expected behavior.
