### ISSUE TITLE
Slidify slides not rendering in browser

### ISSUE THREAD

**Issue by annlia** [ramnathv/slidify#498]
Hi ramnathv,
I have been using your nice slidify package for some-time, and some time ago I created a couple of html slide presentations, which I tried to look at again today, but unfortunately I can only see blank pages in the browser. 

The slides I am trying to visualise can also be found on github
http://annlia.github.io/reproduce/#1 
http://annlia.github.io/pValuesCIs/#1

Any help would be highly appreciated.
Many thanks

**Comment by ramnathv** [comment]
The js/css was being served from Google Code which got deprecated. A simple fix would be to add the following to the YAML front matter in your Rmd file

``` yaml
lib_cdn: "https://cdn.rawgit.com/ramnathv/slidifyLibraries/master/inst/libraries"
```

and rerun slidify.

**Comment by annlia** [comment]
Thanks a lot for your prompt response, this works!
Is there also a more fundamental way to adapt my Rmd file to avoid such problems?

**Comment by ramnathv** [comment]
Use `mode: selfcontained` in the YAML. This will serve assets from the same folder as your presentation and as long as you push the entire folder to github, it will work and keep the presentation selfcontained.

**Comment by annlia** [comment]
Thanks, your feedback is very helpful. 
I was using `mode: standalone` in order to be able to share the presentation with others without having to send them the entire folder, so you are suggesting that this is not a good idea for a longer term/robust solution, and it is actually better to go with `selfcontained,` right?

**Comment by ramnathv** [comment]
So, if you want to use `mode: standalone` and still not run into problems like these, I would recommend that you put the contents of this folder https://github.com/ramnathv/slidifyLibraries/tree/master/inst/libraries in a location that you control, and that allows you to serve js/css.
