### ISSUE TITLE
standalone mode not finding libraries from googlecode.com

### ISSUE THREAD

**Issue by elbamos** [ramnathv/slidify#499]
With `mode: standalone`, slidify generates HTML that loads css and other resources from the web.  When I try to do this, nothing displays.  Going into Chrome developer tools, I see lots and lots of 404 errors that look like this:

```
http://slidifylibraries2.googlecode.com/git/inst/libraries/frameworks/io2012/js/require-1.0.8.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
```

Sure enough, `http://slidifylibraries2.googlecode.com/git` no longer works.  (Perhaps because Google archived googlecode?)

Am I doing something wrong?  Or if not, is there a fix? 

Thanks.

**Comment by ramnathv** [comment]
Yeah. Check [here](https://github.com/ramnathv/slidify/issues/498) for a fix.

**Comment by elbamos** [comment]
Thanks, Ramnath!  With the solution from that Issue, the slides load, but images in `assets/img` don't seem to be getting added to the standalone html.  

Do they have to be references in any particular way to get included?  (These are referenced from embedded `background-image:` css tags.)

**Comment by ramnathv** [comment]
The image files are local to your machine. So they won't show up. For such cases, it is better to use the `selfcontained` mode.

**Comment by elbamos** [comment]
Wow that's a real limitation, at least for those of us who would like to use slidify for commercial work and need to have branded documents.  

I'm going to guess this is the issue we talked about way back, about bringing-in external assets as data uri's. 

Is there any workaround you can suggest?  Perhaps a pandoc solution?  The need is to have the presentation be a single document that can be distributed by email and viewed without an internet connection.

**Comment by ramnathv** [comment]
So there is a `onefile` mode that will allow this to some extent. But for your application, `rmarkdown` based slides seem to be a better option. Slidify is better (in my opinion) when you want to customize templates for your slides.

Another approach that I take that works is to use the `selfcontained` mode and then run the function `htmlwidgets:::pandoc_self_contained_html('index.html', 'index-onefile.html')` to create the kind of file you were talking about.

**Comment by ramnathv** [comment]
As you noted, you can also use `pandoc` directly to turn the html file to a standalone version. My workflow usually is to use the selfcontained mode while writing my slides (it is quick and fast), and turn it into a selfcontained file only during production time.

Hope this helps.

**Comment by elbamos** [comment]
Yes, that really does help - thanks!
