### ISSUE TITLE
User-Defined Functions in Slidify

### ISSUE THREAD

**Issue by pupsik** [ramnathv/slidify#510]
Hello, 

I am building a presentation using slidify and I've been experiencing an issue I can't seem to resolve. In one of my R chunks, I define a simple function (let's say: z = function(x){y=x+2; return(y)} and then use it on a dataframe. The code runs without errors in console and returns expected output, however, when I compile the presentation, I get the an error saying "could not find function". I still struggle with R's scoping rules - perhaps, the error is coming from there? I'll be happy to provide a more detailed example if this isn't enough information. Thank you.

**Comment by ramnathv** [comment]
If you can send me a link to your rmarkdown file, I can take a look.

**Comment by pupsik** [comment]
Thanks so much for a quick reply. 
I wasn't able to create a reproducible example that I could send you for trouble-shooting. The error I get does not appear consistently.  I am going to take down my question until I can attach an example. Once again, thank you for your time.
