### ISSUE TITLE
Is it possible to support two column layout in reveal.js ?

### ISSUE THREAD

**Issue by seifer08ms** [ramnathv/slidify#513]
I'm trying to add an two column layout slide in reveal.js . I followed the example of layout demo but failed. Maybe some framework can't make it. Is it possible to support layout in reveal.js ?

**Comment by peterdoherty01** [comment]
@seifer08ms it's possible. This could guide you.

https://stackoverflow.com/questions/30861845/how-to-use-two-column-layout-with-reveal-js

**Comment by seifer08ms** [comment]
Thanks you! @peter-doherty
